services:
  spring-boot-app:
    container_name: spring-boot-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: true
    networks:
      - monitoring
    # Resource constraints for standalone mode
    mem_limit: 512m # Set maximum memory to 512MB
    mem_reservation: 256m # Reservation of 256MB memory
    cpus: "1.0" # Restrict to a maximum of 1 CPU core.

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    mem_limit: 256m
    mem_reservation: 128m
    cpus: "0.5"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus
    mem_limit: 256m
    mem_reservation: 128m
    cpus: "0.5"

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data:
